from quad_controller_rl.agents.base_agent import BaseAgent
from quad_controller_rl.agents.policy_search import RandomPolicySearch
from quad_controller_rl.agents.DDPG import DDPG
from quad_controller_rl.agents.DDPG_combined import DDPG_combined